services:
  app:
    build:
      context: ./docker/php
    container_name: vendora_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    networks:
      - vendora

  nginx:
    image: nginx:alpine
    container_name: vendora_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - vendora

  mysql:
    image: mysql:8
    container_name: vendora_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vendora
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: vendora
      MYSQL_PASSWORD: secret
    ports:
      - "3308:3306"
    networks:
      - vendora

  node:
    image: node:20-alpine
    container_name: vendora_node
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./frontend:/app
    ports:
      - "3000:3000"
      - "5173:5173"
    command: sh -c "tail -f /dev/null"
    networks:
      - vendora

networks:
  vendora: